# Библиотека Numpy

In [ ]:
L = range(10000)
%timeit [i**2 for i in L]

3.8 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
import numpy as np
L = np.arange(10000)
%timeit L**2

6.93 µs ± 2.29 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Импорт библиотеки

In [ ]:
#Стандартный способ, которого желательно всюду придерживаться
import numpy as np

In [ ]:
#Другие возможные варианты
import numpy
from numpy import sort, sqrt, mean
from numpy import *

In [ ]:
#Так делать не нужно
from numpy import max #будет путаница со стаднартной функцией max в питоне
import numpy as some_magic_liblary

### Массив ndarray

Numpy умеет хранить в памяти массивы **однородных** значений (int, float, строки ограниченной длины, указатели на другие объекты).

Объект массив имеет несколько важных параметров:
* shape - размерность массива
* dtype - тип элементов массива
* stride - описание того, как считывать массив

Пример одномерного массива:

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Параметры массива:

In [ ]:
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(10,)
int32
(4,)


Пример двумерного массива:

In [ ]:
arr_2d = np.arange(10, dtype=float).reshape((2,-1))
arr_2d

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Параметры массива:

In [ ]:
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(2, 5)
float64
(40, 8)


### Способы задания массивов

In [ ]:
# Create an array of evenly-spaced values
np.arange(10, 25, 5)

array([10, 15, 20])

In [ ]:
# Create an array of evenly-spaced values
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Create an array of ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Create an array of zeros
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Create an array with random values
np.random.random((2, 2))

array([[0.77803716, 0.41756693],
       [0.26346067, 0.84054647]])

In [ ]:
# Create a full array
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [ ]:
# Create a diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Индексация элементов массива

In [ ]:
a = np.arange(10)
print(a[0])
print(a[[3, -1]])
print(a[3::2])
print(a[6: -2])
print(a[:-3])

0
[3 9]
[3 5 7 9]
[6 7]
[0 1 2 3 4 5 6]


Индексация многомерных массивов:

In [ ]:
a = np.diag(np.arange(3))
print(a[1, 2])
print(a[1:])

0
[[0 1 0]
 [0 0 2]]


Бывает удобно использовать маски:

In [ ]:
a = np.arange(10, 20)
mask = a % 3 == 0
print(mask)

[False False  True False False  True False False  True False]


Выбор элементов по маске

In [ ]:
print(a[mask])

[12 15 18]


Операции над элементами по маске

In [ ]:
a[a%3 == 0] = -1
print(a)

[10 11 -1 13 14 -1 16 17 -1 19]


### Арифметические операции выполняются поэлементно

In [ ]:
a = np.arange(1, 4)
print(a + 1)
print(2**a)
print(a**2)

[2 3 4]
[2 4 8]
[1 4 9]


### Функции над массивами

In [ ]:
a = np.array([1, 2, 3])
print(np.sum(a), np.sin(a), np.mean(a), np.std(a), np.min(a))

6 [0.84147098 0.90929743 0.14112001] 2.0 0.816496580927726 1


Многие функции являются  методами массива:

In [ ]:
a.mean() == np.mean(a)

True

Для многомерных массивов можно управлять вдоль какой размерности применять метод:

In [ ]:
a=np.arange(24).reshape((2, 3, 4))
print(np.mean(a, axis=(-2, -1)))

[ 5.5 17.5]


Сортировка элементов:

In [ ]:
a = np.random.randn(5)
print(np.sort(a), np.argsort(a))

[-1.19864475 -0.44145599  0.19272541  0.99198881  1.02693535] [4 1 2 3 0]


### Сложение массивов

In [ ]:
a = np.floor(10 * np.random.rand(2, 2))
print('Array a\n', a)

b = np.floor(10 * np.random.rand(2, 2))
print('Array b\n', b)

print('\n--Concatenate a and b vertically --\n')
print(np.vstack((a, b))) # сложение по вертикали
print('\n--Concatenate a and b horizontally--\n')
print(np.hstack((a, b))) # сложение по горизонтали

Array a
 [[9. 7.]
 [1. 6.]]
Array b
 [[3. 0.]
 [3. 6.]]

--Concatenate a and b vertically --

[[9. 7.]
 [1. 6.]
 [3. 0.]
 [3. 6.]]

--Concatenate a and b horizontally--

[[9. 7. 3. 0.]
 [1. 6. 3. 6.]]


### Array broadcasting
Схема ниже показывает, как происходит скложение массивов. Если shape у массивов не совпадают, то массив меньшей размерности "естественным образом" дополняется до большей размерности.

<img src="http://scipy-lectures.org/_images/numpy_broadcasting.png" width="600"/>

In [ ]:
x = np.ones((3, 4))
y = np.arange(4)

# Add `x` and `y`. Note that `x` and `y` have different shapes.
print(x.shape, y.shape)
print(x + y)

(3, 4) (4,)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Как прибавить массив ко всем столбцам матрицы?

In [ ]:
x = np.ones((3, 4))
y = np.arange(3)

print(x + y)

ValueError: ignored

In [ ]:
#правильный способ
print(x + y.reshape(-1, 1))

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


### Домашняя работа
Задача минимум -- решить без использования циклов for/while. Задача максимум -- решить в одну строку (строка с созданием массива, к которому формулируется задание, не учитывается).

In [1]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [5]:
a, b, c = np.ones((10, 1)), np.ones((1, 8)), np.zeros((8, 8))
res = np.concatenate((b, c, b), axis=0)
res = np.concatenate((a, res, a), axis=1)
print(res)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [9]:
a = 4*[0, 1]
b = 4*[1, 0]
res = np.array(4*(a+b)).reshape((8, 8))
print(res)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [38]:
a = np.diag((1, 2, 3, 4))
res = np.concatenate((a, np.zeros((4, 1))), axis=1)
res = np.concatenate((np.zeros((1, 5)), res), axis=0)
print(res)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [8]:
a = np.random.rand(5, 5)
a = a - np.mean(a, axis=1, keepdims=True)
a.mean(axis=1)

array([-1.11022302e-17, -1.11022302e-16,  0.00000000e+00, -4.44089210e-17,
       -1.11022302e-16])

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [19]:
a = np.random.rand(10, 3)
res = a[np.arange(a.shape[0]), np.abs(a - 0.5).argmin(axis=1)]
res

array([0.22317991, 0.70360864, 0.26499109, 0.3491481 , 0.83201911,
       0.4558495 , 0.56495626, 0.484691  , 0.38860963, 0.51282821])

6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [20]:
a = np.random.rand(6, 6)
b = np.max(a, axis=0)
res = np.sum(a, axis=1) / b
res

array([2.71866523, 2.70187237, 3.04023126, 3.65519987, 2.45281578,
       4.37537761])

7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [23]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = np.where(x[:-1] == 0)[0] + 1
x[mask].max()

5

8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [27]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
b = np.bincount(i, minlength=x.size)
x += b
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

Задача со звездочкой.

Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

Пример входа:
```
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
```

Ожидание на выходе:
```
array([[ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5],
       [15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5],
       [25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5]])
```

In [ ]:
#Подсказка: numpy.lib.stride_tricks.sliding_window_view

### Read more

[http://scipy-lectures.org/intro/numpy/array_object.html](http://scipy-lectures.org/intro/numpy/array_object.html)

[https://www.datacamp.com/community/tutorials/python-numpy-tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

[https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)
